docker_repo: docker-ce.repo

#Docker User
docker_user: macan_ubuntu

#Web server
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 8080
web_dockerfile_path: docker/web/

#DB server
web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: dbserver
web_ports: 3306:3306
web_dockerfile_path: docker/db/

